### PR TITLE
Fix detect_injected_dylds

### PR DESCRIPTION
**Pull request by Tony-Y**
I found this bug when using Choicy 1.4.10 that injects a library: "/Library/MobileSubstrate/DynamicLibraries/\ \ \ Choicy.dylib"

### CODE REVIEW

**Comment by Tony-Y** [comment]
I found a comment probably related to this bug in an article on July 14, 2020.
https://philkeeble.com/ios/reverse-engineering/iOS-Anti-Anti-Hooking/
> Anti-hooking measures may be put in place to try stop things like Frida, Cydia Substrate and SSL KillSwitch. I had a bit of an issue with this feature in DVIA-v2 in that **it never detected me** so I am not entirely sure if my Frida script to disable this works, but I think it could. At some point I will try to get this working so that I can prove that it works / fix it if it does not.

**Comment by Tony-Y** [comment]
Try this [Unit Test](https://gist.github.com/Tony-Y/ca5ac1a3306416e083deb4c900fe3518?permalink_comment_id=4612484#gistcomment-4612484).

**Review by prateek147 — APPROVED** [review]

**Comment by prateek147** [comment]
Thanks for this fix @Tony-Y :)

**Comment by Tony-Y** [comment]
@prateek147 
Why don't you want to approve the CodeQL workflow for code scanning?

**Comment by Tony-Y** [comment]
@prateek147 
This repository uses [CodeQL action](https://github.com/github/codeql-action) v1, but the latest version is 2. I think you should update it.

**Pull request merged**
